version: "3.7"

services:
  asymfony-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: fleox/symfony-k8s
    volumes:
      - ./:/var/www/project/:cached
    networks:
      - symfony

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "try,2@Kme"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:

volumes:
  mariadb_data:
