apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1  # Nombre de répliques de votre pod MariaDB
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest  # Version de l'image MariaDB à utiliser
        env:
        - name: MYSQL_ROOT_PASSWORD  # Variable d'environnement pour définir le mot de passe root de la base de données
          value: try,2@Kme
        ports:
        - containerPort: 3306  # Port sur lequel le serveur MariaDB écoute
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306  # Port du service
    targetPort: 3306  # Port cible du pod MariaDB
