apiVersion: v1
kind: Service
metadata:
  name: symfony-app-service
spec:
  selector:
    app: symfony-app
  ports:
  - protocol: TCP
    port: 80  # Port du service au sein du cluster
    targetPort: 80  # Port cible du conteneur Symfony
    nodePort: 30000  # NodePort que vous souhaitez utiliser
  type: NodePort  # Type de service
